apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment 
spec:
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: "development" 
          resources:
            requests:
              cpu: 125m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi