apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yml
  - nginx/ingress.yml
  - argocd/argocd-server-nodeport.yml

images:
- name: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-backend  # 기존 이미지 이름
  newName: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-backend  # 새로운 이미지 이름
  newTag: 65
- name: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-frontend
  newName: 637423620662.dkr.ecr.ap-northeast-2.amazonaws.com/ts-frontend
  newTag: 88

helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    namespace: ingress-nginx
    version: 4.2.5 # 원하는 Helm 차트 버전
    repo: https://kubernetes.github.io/ingress-nginx
    valuesInline:
      controller:
        replicaCount: 1
        service:
          type: NodePort # nodeport 수정 필요
          nodePorts:
            http: 31911 # 원하는 NodePort 설정
            https: 30443 # HTTPS NodePort 설정
          ports:
            http: 80 # HTTP TargetPort 설정
            https: 443 # HTTPS TargetPort 설정
        config:
          enable-cors: "true"
          cors-allow-origin: "https://8fe0-211-244-225-211.ngrok-free.app"
          cors-allow-methods: "GET, POST, PUT, DELETE"
          cors-allow-headers: "Authorization, Content-Type"
          cors-allow-credentials: "true"
  - name: argo-cd
    releaseName: argocd
    namespace: argocd
    version: 5.29.1 # 원하는 ArgoCD Helm 차트 버전
    repo: https://argoproj.github.io/argo-helm
    valuesInline:
      server:
        service:
          type: ClusterIP  # 필요한 경우 NodePort나 LoadBalancer로 변경
      controller:
        replicaCount: 1
patches:
  - target:
      kind: Deployment
      name: backend-deployment
      namespace: backend-deployment
    path: backend/deployment-patch.yml
  - target:
      kind: Deployment
      name: frontend-deployment
      namespace: frontend-deployment
    path: frontend/deployment-patch.yml
  - target:
      kind: Service
      name: backend-service
      namespace: backend-service
    path: backend/service-patch.yml
  - target:
      kind: Service
      name: frontend-service
      namespace: frontend-service
    path: frontend/service-patch.yml
