apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment 
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 # 배포 중 사용할 수 없는 최대 파드 수
      maxSurge: 1 # 배포 중 추가 생성할 수 있는 최대 파드 수
  template:
    metadata:
      labels:
        app: tasty-savings-backend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: backend
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local" 
          resources:
            requests:
              cpu: 250m 
              memory: 128Mi 
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            initialDelaySeconds: 20 # 컨테이너 시작 후 첫 체크까지 대기 시간
            periodSeconds: 10 # 헬스 체크 간격
            timeoutSeconds: 3 # 체크 타임 아웃 설정
