apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-load-test-script
data:
  load-test.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export default function () {
      http.get('http://backend-service.default.svc.cluster.local:8080');
      sleep(1);
    }